[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-src https://jadaburger.com https://www.jadaburger.com https://country-quiz-pink.vercel.app https://tu-demo2.vercel.app https://*.netlify.app"
